# Site settings
title: Eat/Chat/Code
header-img: img/home-bg.png
email: azharshahstl@yahoo.com
copyright_name: azharshahstl
description: > # this means to ignore newlines until "baseurl:"
  3 of my favorite things
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  azharshahstl
learn_profile: azharshahstl
email_username: azharshahstl@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
